import Header from "@/Components/Header";
import "./globals.css";

export const metadata = {
  title: "Imdb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />

        {/* Navbar */}

        {/* Search Bar */}

        {children}
      </body>
    </html>
  );
}
